version: "3.9"

services:
  frontend:
    build: frontend/
    ports:
      - "3000:3000"
  backend:
    build: backend/
    environment:
      - MONGODB_CONN_STRING=mongodb://root:root@db:27017/db
      - JWT_SECRET=secret
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: mongo
    ports: 
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=db
    volumes:
      - db_data:/data/db
      - ./backend/initdb.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
volumes:
  db_data:
